name: Deploy Django

on:
  push:
    branches:
      - dev1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/cloudwatch

            git pull origin dev1

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py migrate --noinput
       
            sudo systemctl restart django